<!-- AutoGenerated Form Developed By *** B.Deka *** Copyright-->
	<html>
	<head>
	<title>edit_criterionEditForm</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

		<script src="http://cdn.ckeditor.com/4.7.1/standard-all/ckeditor.js"></script>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	</head>
	<body>
	     <?php
			$id=$_GET['crite_slno'];
			if(!isset($_GET['crite_slno']))	 { echo 'Invalid_URL'; return true;}
			include_once("../class/class.criterion.php");
			$tb_handle=new criterion();
			$tb_handle->select($id);
		?>

				<br><br>
				<div id="main" class="container border">
					<div id="form_input" class="col-lg-12" >
						<form name="criterion_update_frm" action="../uiProcess/criterion_UpdateProcess.php" method="post">

							<input type="hidden" name="crite_slno" value="<?php echo $tb_handle->getcrite_slno();?>">

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">SL. No. :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_slno" type="text" class="form-control" name="crite_slno" value="<?php echo $tb_handle->getcrite_slno();?>" aria-describedby="basic-addon2" required>
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Title :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_title" type="text" class="form-control" name="crite_title" value="<?php echo $tb_handle->getcrite_title();?>" aria-describedby="basic-addon2" required>
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Block :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_block" type="text" class="form-control" name="crite_block" value="<?php echo $tb_handle->getcrite_block();?>" aria-describedby="basic-addon2" required>
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Description :</label>
								</div>

								<div class="form-group col-md-10">
									<textarea id="crite_descrip" class="form-control" name="crite_descrip" aria-describedby="basic-addon2" required><?php echo $tb_handle->getcrite_descrip();?></textarea>
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve1 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved1" type="text" class="form-control" name="crite_reserved1" value="<?php echo $tb_handle->getcrite_reserved1();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve2 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved2" type="text" class="form-control" name="crite_reserved2" value="<?php echo $tb_handle->getcrite_reserved2();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve3 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved3" type="text" class="form-control" name="crite_reserved3" value="<?php echo $tb_handle->getcrite_reserved3();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve4 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved4" type="text" class="form-control" name="crite_reserved4" value="<?php echo $tb_handle->getcrite_reserved4();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve5 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved5" type="text" class="form-control" name="crite_reserved5" value="<?php echo $tb_handle->getcrite_reserved5();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve6 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved6" type="text" class="form-control" name="crite_reserved6" value="<?php echo $tb_handle->getcrite_reserved6();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve7 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved7" type="text" class="form-control" name="crite_reserved7" value="<?php echo $tb_handle->getcrite_reserved7();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve8 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved8" type="text" class="form-control" name="crite_reserved8" value="<?php echo $tb_handle->getcrite_reserved8();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve9 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved9" type="text" class="form-control" name="crite_reserved9" value="<?php echo $tb_handle->getcrite_reserved9();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve10 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved10" type="text" class="form-control" name="crite_reserved10" value="<?php echo $tb_handle->getcrite_reserved10();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve11 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved11" type="text" class="form-control" name="crite_reserved11" value="<?php echo $tb_handle->getcrite_reserved11();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve12 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved12" type="text" class="form-control" name="crite_reserved12" value="<?php echo $tb_handle->getcrite_reserved12();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve13 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved13" type="text" class="form-control" name="crite_reserved13" value="<?php echo $tb_handle->getcrite_reserved13();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve14 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved14" type="text" class="form-control" name="crite_reserved14" value="<?php echo $tb_handle->getcrite_reserved14();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve15 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved15" type="text" class="form-control" name="crite_reserved15" value="<?php echo $tb_handle->getcrite_reserved15();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve16 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved16" type="text" class="form-control" name="crite_reserved16" value="<?php echo $tb_handle->getcrite_reserved16();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve17 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved17" type="text" class="form-control" name="crite_reserved17" value="<?php echo $tb_handle->getcrite_reserved17();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve18 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved18" type="text" class="form-control" name="crite_reserved18" value="<?php echo $tb_handle->getcrite_reserved18();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve19 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved19" type="text" class="form-control" name="crite_reserved19" value="<?php echo $tb_handle->getcrite_reserved19();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row text-left">
								<div class="form-group col-md-2">
									<label for="sl_no" class="col-form-label">Reserve20 :</label>
								</div>

								<div class="form-group col-md-10">
									<input id="crite_reserved20" type="text" class="form-control" name="crite_reserved20" value="<?php echo $tb_handle->getcrite_reserved20();?>" aria-describedby="basic-addon2">
								</div>
							</div>

							<div class="row">
								<div class="form-group col-md-2">

								</div>

								<div class="form-group col-md-3">
									<input type="submit" class="btn btn-primary btn-md btn-block" name="submit" value="UPDATE">
								</div>

								<div class="form-group col-md-4">
									<input type="reset" class="btn btn-primary btn-md btn-block" name="reset" value="RESET">
								</div>

								<div class="form-group col-md-3">
									<a href="criterionForm.php" class="btn btn-primary btn-md btn-block">BACK</a>
								</div>
							</div>

						</form>
					</div>

				</div>
				<script>
				CKEDITOR.replace( 'crite_descrip', {
					language: 'en'
				});
			</script>
      </body>
</html>
