<!-- AutoGenerated Form Developed By *** B.Deka *** Copyright-->
	<html>
	<head>
	<title>edit_keyindicatorEditForm</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	</head>
	<body>
	     <?php
			$id=$_GET['key_slno'];
			if(!isset($_GET['key_slno']))	 { echo 'Invalid_URL'; return true;}
			include_once("../class/class.keyindicator.php");
			$tb_handle=new keyindicator();
			$tb_handle->select($id);
		?>

		<br><br>
		<div id="main" class="container border">
			<div id="form_input" class="col-lg-12" >
				<form name="keyindicator_update_frm" action="../uiProcess/keyindicator_UpdateProcess.php" method="post">

					<input type="hidden" name="key_slno" value="<?php echo $tb_handle->getkey_slno();?>">

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="key_slno" class="col-form-label">Key SL. No. :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_slno" type="text" class="form-control" name="key_slno" value="<?php echo $tb_handle->getkey_slno();?>" aria-describedby="basic-addon2" required>
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="key_indicator" class="col-form-label">Key Indicator :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_indicator" type="text" class="form-control" name="key_indicator" value="<?php echo $tb_handle->getkey_indicator();?>" aria-describedby="basic-addon2" required>
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="key_title" class="col-form-label">Key Title :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_title" type="text" class="form-control" name="key_title" value="<?php echo $tb_handle->getkey_title();?>" aria-describedby="basic-addon2" required>
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="key_crite_slno" class="col-form-label">Key Criterion SL. No. :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_crite_slno" type="text" class="form-control" name="key_crite_slno" value="<?php echo $tb_handle->getkey_crite_slno();?>" aria-describedby="basic-addon2" required>
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="key_block" class="col-form-label">Key Block :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_block" type="text" class="form-control" name="key_block" value="<?php echo $tb_handle->getkey_block();?>" aria-describedby="basic-addon2" required>
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="key_reserved1" class="col-form-label">Reserve1 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved1" type="text" class="form-control" name="key_reserved1" value="<?php echo $tb_handle->getkey_reserved1();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve2 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved2" type="text" class="form-control" name="key_reserved2" value="<?php echo $tb_handle->getkey_reserved2();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve3 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved3" type="text" class="form-control" name="key_reserved3" value="<?php echo $tb_handle->getkey_reserved3();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve4 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved4" type="text" class="form-control" name="key_reserved4" value="<?php echo $tb_handle->getkey_reserved4();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve5 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved5" type="text" class="form-control" name="key_reserved5" value="<?php echo $tb_handle->getkey_reserved5();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve6 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved6" type="text" class="form-control" name="key_reserved6" value="<?php echo $tb_handle->getkey_reserved6();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve7 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved7" type="text" class="form-control" name="key_reserved7" value="<?php echo $tb_handle->getkey_reserved7();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve8 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved8" type="text" class="form-control" name="key_reserved8" value="<?php echo $tb_handle->getkey_reserved8();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve9 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved9" type="text" class="form-control" name="key_reserved9" value="<?php echo $tb_handle->getkey_reserved9();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve10 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved10" type="text" class="form-control" name="key_reserved10" value="<?php echo $tb_handle->getkey_reserved10();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve11 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved11" type="text" class="form-control" name="key_reserved11" value="<?php echo $tb_handle->getkey_reserved11();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve12 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved12" type="text" class="form-control" name="key_reserved12" value="<?php echo $tb_handle->getkey_reserved12();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve13 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved13" type="text" class="form-control" name="key_reserved13" value="<?php echo $tb_handle->getkey_reserved13();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve14 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved14" type="text" class="form-control" name="key_reserved14" value="<?php echo $tb_handle->getkey_reserved14();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve15 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved15" type="text" class="form-control" name="key_reserved15" value="<?php echo $tb_handle->getkey_reserved15();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve16 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved16" type="text" class="form-control" name="key_reserved16" value="<?php echo $tb_handle->getkey_reserved16();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve17 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved17" type="text" class="form-control" name="key_reserved17" value="<?php echo $tb_handle->getkey_reserved17();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve18 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved18" type="text" class="form-control" name="key_reserved18" value="<?php echo $tb_handle->getkey_reserved18();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve19 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved19" type="text" class="form-control" name="key_reserved19" value="<?php echo $tb_handle->getkey_reserved19();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve20 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="key_reserved20" type="text" class="form-control" name="key_reserved20" value="<?php echo $tb_handle->getkey_reserved20();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row">
						<div class="form-group col-md-2">
						</div>

						<div class="form-group col-md-3">
							<input type="submit" class="btn btn-primary btn-md btn-block" name="submit" value="UPDATE">
						</div>

						<div class="form-group col-md-4">
							<input type="reset" class="btn btn-primary btn-md btn-block" name="reset" value="RESET">
						</div>

						<div class="form-group col-md-3">
							<a href="keyindicatorForm.php" class="btn btn-primary btn-md btn-block">BACK</a>
						</div>
					</div>

				</form>
			</div>

		</div>
      </body>
</html>
