<!-- AutoGenerated Form Developed By *** B.Deka *** CopyRight Protection-->
	<html>
	<head>
	<title>data_template_uploadForm</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">


		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script type="text/javascript">
    $(document).ready( function () {
      $('#data_template_uploadFormDisplay').DataTable();
    });
    </script>
	</head>
	<body>

		<br><br>

		<div id="main" class="container border">
      <div id="form_input" class="col-lg-12" >
        <form name="data_template_upload_frm" action="data_template_uploadFormProcess.php" method="post">

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_slno" class="col-form-label">Data Upload SL. No. :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_slno" class="form-control" name="data_upload_slno" placeholder="Enter Data Upload Serial No." aria-describedby="basic-addon2" required>
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_temp_slno" class="col-form-label">Data Upload Temporary SL. No. :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_temp_slno" class="form-control" name="data_upload_temp_slno" placeholder="Enter Data Upload Temporary SL. No." aria-describedby="basic-addon2" required>
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_title" class="col-form-label">Data Upload Title :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_title" class="form-control" name="data_upload_title" placeholder="Enter Data Upload Title" aria-describedby="basic-addon2" required>
            </div>
          </div>

					<div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_url" class="col-form-label">Data Upload URL :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_url" class="form-control" name="data_upload_url" placeholder="Enter Data Upload URL" aria-describedby="basic-addon2" required>
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved1" class="col-form-label">Reserve1 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved1" class="form-control" name="data_upload_reserved1" placeholder="Enter Reserve1" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved2" class="col-form-label">Reserve2 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved2" class="form-control" name="data_upload_reserved2" placeholder="Enter Reserve2" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved3" class="col-form-label">Reserve3 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved3" class="form-control" name="data_upload_reserved3" placeholder="Enter Reserve3" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved4" class="col-form-label">Reserve4 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved4" class="form-control" name="data_upload_reserved4" placeholder="Enter Reserve4" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved5" class="col-form-label">Reserve5 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved5" class="form-control" name="data_upload_reserved5" placeholder="Enter Reserve5" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved6" class="col-form-label">Reserve6 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved6" class="form-control" name="data_upload_reserved6" placeholder="Enter Reserve6" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved7" class="col-form-label">Reserve7 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved7" class="form-control" name="data_upload_reserved7" placeholder="Enter Reserve7" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved8" class="col-form-label">Reserve8 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved8" class="form-control" name="data_upload_reserved8" placeholder="Enter Reserve8" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved9" class="col-form-label">Reserve9 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved9" class="form-control" name="data_upload_reserved9" placeholder="Enter Reserve9" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved10" class="col-form-label">Reserve10 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved10" class="form-control" name="data_upload_reserved10" placeholder="Enter Reserve10" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved11" class="col-form-label">Reserve11 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved11" class="form-control" name="data_upload_reserved11" placeholder="Enter Reserve11" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved12" class="col-form-label">Reserve12 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved12" class="form-control" name="data_upload_reserved12" placeholder="Enter Reserve12" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved13" class="col-form-label">Reserve13 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved13" class="form-control" name="data_upload_reserved13" placeholder="Enter Reserve13" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved14" class="col-form-label">Reserve14 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved14" class="form-control" name="data_upload_reserved14" placeholder="Enter Reserve14" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved15" class="col-form-label">Reserve15 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved15" class="form-control" name="data_upload_reserved15" placeholder="Enter Reserve15" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved16" class="col-form-label">Reserve16 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved16" class="form-control" name="data_upload_reserved16" placeholder="Enter Reserve16" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved17" class="col-form-label">Reserve17 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved17" class="form-control" name="data_upload_reserved17" placeholder="Enter Reserve17" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved18" class="col-form-label">Reserve18 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved18" class="form-control" name="data_upload_reserved18" placeholder="Enter Reserve18" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved19" class="col-form-label">Reserve19 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved19" class="form-control" name="data_upload_reserved19" placeholder="Enter Reserve19" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row text-left">
            <div class="form-group col-md-2">
              <label for="data_upload_reserved20" class="col-form-label">Reserve20 :</label>
            </div>

            <div class="form-group col-md-10">
              <input type="text" id="data_upload_reserved20" class="form-control" name="data_upload_reserved20" placeholder="Enter Reserve20" aria-describedby="basic-addon2">
            </div>
          </div>

          <div class="row">
            <div class="form-group col-md-2">
            </div>

            <div class="form-group col-md-5">
              <input type="submit" class="btn btn-primary btn-md btn-block" name="submit" value="SUBMIT">
            </div>

            <div class="form-group col-md-5">
              <input type="reset" class="btn btn-primary btn-md btn-block" name="reset" value="RESET">
            </div>
          </div>

        </form>
      </div>

      <div class="table-responsive">
        <table id="data_template_uploadFormDisplay" class="table table-hover">
          <thead>
            <tr>
              <th scope="col">Data Upload SL. No.</th>
							<th scope="col">Data Upload Temporary SL. No.</th>
              <th scope="col">Data Upload Title</th>
              <th scope="col">Data Upload URL</th>
              <th scope="col">Reserved1</th>
              <th scope="col">Reserved2</th>
              <th scope="col">Reserved3</th>
              <th scope="col">Reserved4</th>
              <th scope="col">Reserved5</th>
              <th scope="col">Reserved6</th>
              <th scope="col">Reserved7</th>
              <th scope="col">Reserved8</th>
              <th scope="col">Reserved9</th>
              <th scope="col">Reserved10</th>
              <th scope="col">Reserved11</th>
              <th scope="col">Reserved12</th>
              <th scope="col">Reserved13</th>
              <th scope="col">Reserved14</th>
              <th scope="col">Reserved15</th>
              <th scope="col">Reserved16</th>
              <th scope="col">Reserved17</th>
              <th scope="col">Reserved18</th>
              <th scope="col">Reserved19</th>
              <th scope="col">Reserved20</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
            <?php
              include_once("class.data_template_upload.php");
              $disp_handle  = new data_template_upload();
              $disp_handle-> selectDisplay();
            ?>
        </table>
      </div>

    </div>

      </body>
</html>
