<!-- AutoGenerated Form Developed By *** B.Deka *** Copyright-->
	<html>
	<head>
	<title>edit_metricuploadEditForm</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	</head>
	<body>
	     <?php
			$id=$_GET['up_metric_slno'];
			if(!isset($_GET['up_metric_slno']))	 { echo 'Invalid_URL'; return true;}
			include_once("class.metricupload.php");
			$tb_handle=new metricupload();
			$tb_handle->select($id);
		?>

		<br><br>
		<div id="main" class="container border">
			<div id="form_input" class="col-lg-12" >
				<form name="metricupload_update_frm" action="metricupload_UpdateProcess.php" method="post">

					<input type="hidden" name="up_metric_slno" value="<?php echo $tb_handle->getup_metric_slno();?>">

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="up_metric_slno" class="col-form-label">Upload Metric SL. No. :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_slno" type="text" class="form-control" name="up_metric_slno" value="<?php echo $tb_handle->getup_metric_slno();?>" aria-describedby="basic-addon2" required>
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="up_metric_metric_slno" class="col-form-label">Upload Metric Metric SL. No. :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_metric_slno" type="text" class="form-control" name="up_metric_metric_slno" value="<?php echo $tb_handle->getup_metric_metric_slno();?>" aria-describedby="basic-addon2" required>
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="up_metric_title" class="col-form-label">Upload Metric Title :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_title" type="text" class="form-control" name="up_metric_title" value="<?php echo $tb_handle->getup_metric_title();?>" aria-describedby="basic-addon2" required>
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="up_metric_url" class="col-form-label">Upload Metric URL :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_url" type="text" class="form-control" name="up_metric_url" value="<?php echo $tb_handle->getup_metric_url();?>" aria-describedby="basic-addon2" required>
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="up_metric_block" class="col-form-label">Upload Metric Block :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_block" type="text" class="form-control" name="up_metric_block" value="<?php echo $tb_handle->getup_metric_block();?>" aria-describedby="basic-addon2" required>
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="up_metric_reserved1" class="col-form-label">Reserve1 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved1" type="text" class="form-control" name="up_metric_reserved1" value="<?php echo $tb_handle->getup_metric_reserved1();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="up_metric_reserved2" class="col-form-label">Reserve2 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved2" type="text" class="form-control" name="up_metric_reserved2" value="<?php echo $tb_handle->getup_metric_reserved2();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve3 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved3" type="text" class="form-control" name="up_metric_reserved3" value="<?php echo $tb_handle->getup_metric_reserved3();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve4 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved4" type="text" class="form-control" name="up_metric_reserved4" value="<?php echo $tb_handle->getup_metric_reserved4();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve5 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved5" type="text" class="form-control" name="up_metric_reserved5" value="<?php echo $tb_handle->getup_metric_reserved5();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve6 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved6" type="text" class="form-control" name="up_metric_reserved6" value="<?php echo $tb_handle->getup_metric_reserved6();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve7 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved7" type="text" class="form-control" name="up_metric_reserved7" value="<?php echo $tb_handle->getup_metric_reserved7();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve8 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved8" type="text" class="form-control" name="up_metric_reserved8" value="<?php echo $tb_handle->getup_metric_reserved8();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve9 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved9" type="text" class="form-control" name="up_metric_reserved9" value="<?php echo $tb_handle->getup_metric_reserved9();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve10 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved10" type="text" class="form-control" name="up_metric_reserved10" value="<?php echo $tb_handle->getup_metric_reserved10();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve11 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved11" type="text" class="form-control" name="up_metric_reserved11" value="<?php echo $tb_handle->getup_metric_reserved11();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve12 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved12" type="text" class="form-control" name="up_metric_reserved12" value="<?php echo $tb_handle->getup_metric_reserved12();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve13 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved13" type="text" class="form-control" name="up_metric_reserved13" value="<?php echo $tb_handle->getup_metric_reserved13();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve14 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved14" type="text" class="form-control" name="up_metric_reserved14" value="<?php echo $tb_handle->getup_metric_reserved14();?>" aria-describedby="basic-addon2">
						</div>
					</div4>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve15 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved15" type="text" class="form-control" name="up_metric_reserved15" value="<?php echo $tb_handle->getup_metric_reserved15();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve16 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved16" type="text" class="form-control" name="up_metric_reserved16" value="<?php echo $tb_handle->getup_metric_reserved16();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve17 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved17" type="text" class="form-control" name="up_metric_reserved17" value="<?php echo $tb_handle->getup_metric_reserved17();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve18 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved18" type="text" class="form-control" name="up_metric_reserved18" value="<?php echo $tb_handle->getup_metric_reserved18();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve19 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved19" type="text" class="form-control" name="up_metric_reserved19" value="<?php echo $tb_handle->getup_metric_reserved19();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row text-left">
						<div class="form-group col-md-2">
							<label for="sl_no" class="col-form-label">Reserve20 :</label>
						</div>

						<div class="form-group col-md-10">
							<input id="up_metric_reserved20" type="text" class="form-control" name="up_metric_reserved20" value="<?php echo $tb_handle->getup_metric_reserved20();?>" aria-describedby="basic-addon2">
						</div>
					</div>

					<div class="row">
						<div class="form-group col-md-2">
						</div>

						<div class="form-group col-md-3">
							<input type="submit" class="btn btn-primary btn-md btn-block" name="submit" value="UPDATE">
						</div>

						<div class="form-group col-md-4">
							<input type="reset" class="btn btn-primary btn-md btn-block" name="reset" value="RESET">
						</div>

						<div class="form-group col-md-3">
							<a href="metricuploadForm.php" class="btn btn-primary btn-md btn-block">BACK</a>
						</div>
					</div>

				</form>
			</div>

		</div>

      </body>
</html>
