<!-- AutoGenerated Form Developed By *** B.Deka *** CopyRight Protection-->
	<html>
	<head>
	<title>criterionForm</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	</head>
	<body bgcolor="gray" text="#000000">
	<table width="480" border="1" align="center" height="269">
	  <tr>
	    <td height="234" colspan="2">
		 <form name=criterion_frm  action=criterionFormProcess.php method=post>
 			 <table>
				<tr><td>crite_slno&nbsp;</td><td><input type=text size=30 name=crite_slno id=crite_slno></td></tr>
				<tr><td>crite_title&nbsp;</td><td><input type=text size=30 name=crite_title id=crite_title></td></tr>
				<tr><td>crite_block&nbsp;</td><td><input type=text size=30 name=crite_block id=crite_block></td></tr>
				<tr><td>crite_descrip&nbsp;</td><td><input type=text size=30 name=crite_descrip id=crite_descrip></td></tr>
				<tr><td>crite_reserved1&nbsp;</td><td><input type=text size=30 name=crite_reserved1 id=crite_reserved1></td></tr>
				<tr><td>crite_reserved2&nbsp;</td><td><input type=text size=30 name=crite_reserved2 id=crite_reserved2></td></tr>
				<tr><td>crite_reserved3&nbsp;</td><td><input type=text size=30 name=crite_reserved3 id=crite_reserved3></td></tr>
				<tr><td>crite_reserved4&nbsp;</td><td><input type=text size=30 name=crite_reserved4 id=crite_reserved4></td></tr>
				<tr><td>crite_reserved5&nbsp;</td><td><input type=text size=30 name=crite_reserved5 id=crite_reserved5></td></tr>
				<tr><td>crite_reserved6&nbsp;</td><td><input type=text size=30 name=crite_reserved6 id=crite_reserved6></td></tr>
				<tr><td>crite_reserved7&nbsp;</td><td><input type=text size=30 name=crite_reserved7 id=crite_reserved7></td></tr>
				<tr><td>crite_reserved8&nbsp;</td><td><input type=text size=30 name=crite_reserved8 id=crite_reserved8></td></tr>
				<tr><td>crite_reserved9&nbsp;</td><td><input type=text size=30 name=crite_reserved9 id=crite_reserved9></td></tr>
				<tr><td>crite_reserved10&nbsp;</td><td><input type=text size=30 name=crite_reserved10 id=crite_reserved10></td></tr>
				<tr><td>crite_reserved11&nbsp;</td><td><input type=text size=30 name=crite_reserved11 id=crite_reserved11></td></tr>
				<tr><td>crite_reserved12&nbsp;</td><td><input type=text size=30 name=crite_reserved12 id=crite_reserved12></td></tr>
				<tr><td>crite_reserved13&nbsp;</td><td><input type=text size=30 name=crite_reserved13 id=crite_reserved13></td></tr>
				<tr><td>crite_reserved14&nbsp;</td><td><input type=text size=30 name=crite_reserved14 id=crite_reserved14></td></tr>
				<tr><td>crite_reserved15&nbsp;</td><td><input type=text size=30 name=crite_reserved15 id=crite_reserved15></td></tr>
				<tr><td>crite_reserved16&nbsp;</td><td><input type=text size=30 name=crite_reserved16 id=crite_reserved16></td></tr>
				<tr><td>crite_reserved17&nbsp;</td><td><input type=text size=30 name=crite_reserved17 id=crite_reserved17></td></tr>
				<tr><td>crite_reserved18&nbsp;</td><td><input type=text size=30 name=crite_reserved18 id=crite_reserved18></td></tr>
				<tr><td>crite_reserved19&nbsp;</td><td><input type=text size=30 name=crite_reserved19 id=crite_reserved19></td></tr>
				<tr><td>crite_reserved20&nbsp;</td><td><input type=text size=30 name=crite_reserved20 id=crite_reserved20></td></tr>	
			</table>



	    </td>
	  </tr>
	</table>
        <p align=center><input type=submit value="Save"><input type=reset value="Reset"></p>
	</form>
      </body>
</html>
