<!-- AutoGenerated Form Developed By *** B.Deka *** Copyright--> 
	<html>
	<head>
	<title>edit_criterionEditForm</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	</head>
	<body bgcolor="gray" text="#000000">
	     <?php 
			$id=$_GET['crite_slno'];
			if(!isset($_GET['crite_slno']))	 { echo 'Invalid_URL'; return true;}
			include_once("class.criterion.php");
			$tb_handle=new criterion();
			$tb_handle->select($id);
		?>


	<table width="480" border="1" align="center" height="269">
	  <tr>
	    <td height="234" colspan="2">
		 <form name='criterion_update_frm'  action='criterion_UpdateProcess.php' method=post>
		<input type=hidden size=30 name=crite_slno id=crite_slno value="<?php echo $tb_handle->getcrite_slno();?>">
 		<table>	
		<tr><td>crite_slno&nbsp;</td><td>
		<input type=text size=30 id=crite_slno name=crite_slno value="<?php echo $tb_handle->getcrite_slno();?>">
		</td></tr>	
		<tr><td>crite_title&nbsp;</td><td>
		<input type=text size=30 id=crite_title name=crite_title value="<?php echo $tb_handle->getcrite_title();?>">
		</td></tr>	
		<tr><td>crite_block&nbsp;</td><td>
		<input type=text size=30 id=crite_block name=crite_block value="<?php echo $tb_handle->getcrite_block();?>">
		</td></tr>	
		<tr><td>crite_descrip&nbsp;</td><td>
		<input type=text size=30 id=crite_descrip name=crite_descrip value="<?php echo $tb_handle->getcrite_descrip();?>">
		</td></tr>	
		<tr><td>crite_reserved1&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved1 name=crite_reserved1 value="<?php echo $tb_handle->getcrite_reserved1();?>">
		</td></tr>	
		<tr><td>crite_reserved2&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved2 name=crite_reserved2 value="<?php echo $tb_handle->getcrite_reserved2();?>">
		</td></tr>	
		<tr><td>crite_reserved3&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved3 name=crite_reserved3 value="<?php echo $tb_handle->getcrite_reserved3();?>">
		</td></tr>	
		<tr><td>crite_reserved4&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved4 name=crite_reserved4 value="<?php echo $tb_handle->getcrite_reserved4();?>">
		</td></tr>	
		<tr><td>crite_reserved5&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved5 name=crite_reserved5 value="<?php echo $tb_handle->getcrite_reserved5();?>">
		</td></tr>	
		<tr><td>crite_reserved6&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved6 name=crite_reserved6 value="<?php echo $tb_handle->getcrite_reserved6();?>">
		</td></tr>	
		<tr><td>crite_reserved7&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved7 name=crite_reserved7 value="<?php echo $tb_handle->getcrite_reserved7();?>">
		</td></tr>	
		<tr><td>crite_reserved8&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved8 name=crite_reserved8 value="<?php echo $tb_handle->getcrite_reserved8();?>">
		</td></tr>	
		<tr><td>crite_reserved9&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved9 name=crite_reserved9 value="<?php echo $tb_handle->getcrite_reserved9();?>">
		</td></tr>	
		<tr><td>crite_reserved10&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved10 name=crite_reserved10 value="<?php echo $tb_handle->getcrite_reserved10();?>">
		</td></tr>	
		<tr><td>crite_reserved11&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved11 name=crite_reserved11 value="<?php echo $tb_handle->getcrite_reserved11();?>">
		</td></tr>	
		<tr><td>crite_reserved12&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved12 name=crite_reserved12 value="<?php echo $tb_handle->getcrite_reserved12();?>">
		</td></tr>	
		<tr><td>crite_reserved13&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved13 name=crite_reserved13 value="<?php echo $tb_handle->getcrite_reserved13();?>">
		</td></tr>	
		<tr><td>crite_reserved14&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved14 name=crite_reserved14 value="<?php echo $tb_handle->getcrite_reserved14();?>">
		</td></tr>	
		<tr><td>crite_reserved15&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved15 name=crite_reserved15 value="<?php echo $tb_handle->getcrite_reserved15();?>">
		</td></tr>	
		<tr><td>crite_reserved16&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved16 name=crite_reserved16 value="<?php echo $tb_handle->getcrite_reserved16();?>">
		</td></tr>	
		<tr><td>crite_reserved17&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved17 name=crite_reserved17 value="<?php echo $tb_handle->getcrite_reserved17();?>">
		</td></tr>	
		<tr><td>crite_reserved18&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved18 name=crite_reserved18 value="<?php echo $tb_handle->getcrite_reserved18();?>">
		</td></tr>	
		<tr><td>crite_reserved19&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved19 name=crite_reserved19 value="<?php echo $tb_handle->getcrite_reserved19();?>">
		</td></tr>	
		<tr><td>crite_reserved20&nbsp;</td><td>
		<input type=text size=30 id=crite_reserved20 name=crite_reserved20 value="<?php echo $tb_handle->getcrite_reserved20();?>">
		</td></tr>	
		</table>		

	    </td>
	  </tr>
	</table>
       <p align=center> <input type=submit value="Update"></p>
	     </form>
      </body>
</html>