<!-- AutoGenerated Form Developed By *** B.Deka *** CopyRight Protection--> 
	<html>
	<head>
	<title>data_template_uploadForm</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	</head>
	<body bgcolor="gray" text="#000000">
	<table width="480" border="1" align="center" height="269">
	  <tr>
	    <td height="234" colspan="2">
		 <form name=data_template_upload_frm  action=data_template_uploadFormProcess.php method=post>
 			 <table>	
				<tr><td>data_upload_slno&nbsp;</td><td><input type=text size=30 name=data_upload_slno id=data_upload_slno></td></tr>	
				<tr><td>data_upload_temp_slno&nbsp;</td><td><input type=text size=30 name=data_upload_temp_slno id=data_upload_temp_slno></td></tr>	
				<tr><td>data_upload_title&nbsp;</td><td><input type=text size=30 name=data_upload_title id=data_upload_title></td></tr>	
				<tr><td>data_upload_url&nbsp;</td><td><input type=text size=30 name=data_upload_url id=data_upload_url></td></tr>	
				<tr><td>data_upload_reserved1&nbsp;</td><td><input type=text size=30 name=data_upload_reserved1 id=data_upload_reserved1></td></tr>	
				<tr><td>data_upload_reserved2&nbsp;</td><td><input type=text size=30 name=data_upload_reserved2 id=data_upload_reserved2></td></tr>	
				<tr><td>data_upload_reserved3&nbsp;</td><td><input type=text size=30 name=data_upload_reserved3 id=data_upload_reserved3></td></tr>	
				<tr><td>data_upload_reserved4&nbsp;</td><td><input type=text size=30 name=data_upload_reserved4 id=data_upload_reserved4></td></tr>	
				<tr><td>data_upload_reserved5&nbsp;</td><td><input type=text size=30 name=data_upload_reserved5 id=data_upload_reserved5></td></tr>	
				<tr><td>data_upload_reserved6&nbsp;</td><td><input type=text size=30 name=data_upload_reserved6 id=data_upload_reserved6></td></tr>	
				<tr><td>data_upload_reserved7&nbsp;</td><td><input type=text size=30 name=data_upload_reserved7 id=data_upload_reserved7></td></tr>	
				<tr><td>data_upload_reserved8&nbsp;</td><td><input type=text size=30 name=data_upload_reserved8 id=data_upload_reserved8></td></tr>	
				<tr><td>data_upload_reserved9&nbsp;</td><td><input type=text size=30 name=data_upload_reserved9 id=data_upload_reserved9></td></tr>	
				<tr><td>data_upload_reserved10&nbsp;</td><td><input type=text size=30 name=data_upload_reserved10 id=data_upload_reserved10></td></tr>	
				<tr><td>data_upload_reserved11&nbsp;</td><td><input type=text size=30 name=data_upload_reserved11 id=data_upload_reserved11></td></tr>	
				<tr><td>data_upload_reserved12&nbsp;</td><td><input type=text size=30 name=data_upload_reserved12 id=data_upload_reserved12></td></tr>	
				<tr><td>data_upload_reserved13&nbsp;</td><td><input type=text size=30 name=data_upload_reserved13 id=data_upload_reserved13></td></tr>	
				<tr><td>data_upload_reserved14&nbsp;</td><td><input type=text size=30 name=data_upload_reserved14 id=data_upload_reserved14></td></tr>	
				<tr><td>data_upload_reserved15&nbsp;</td><td><input type=text size=30 name=data_upload_reserved15 id=data_upload_reserved15></td></tr>	
				<tr><td>data_upload_reserved16&nbsp;</td><td><input type=text size=30 name=data_upload_reserved16 id=data_upload_reserved16></td></tr>	
				<tr><td>data_upload_reserved17&nbsp;</td><td><input type=text size=30 name=data_upload_reserved17 id=data_upload_reserved17></td></tr>	
				<tr><td>data_upload_reserved18&nbsp;</td><td><input type=text size=30 name=data_upload_reserved18 id=data_upload_reserved18></td></tr>	
				<tr><td>data_upload_reserved19&nbsp;</td><td><input type=text size=30 name=data_upload_reserved19 id=data_upload_reserved19></td></tr>	
				<tr><td>data_upload_reserved20&nbsp;</td><td><input type=text size=30 name=data_upload_reserved20 id=data_upload_reserved20></td></tr>	
			</table>

		

	    </td>
	  </tr>
	</table>
        <p align=center><input type=submit value="Save"><input type=reset value="Reset"></p>
	</form>
      </body>
</html>