<!-- AutoGenerated Form Developed By *** B.Deka *** Copyright--> 
	<html>
	<head>
	<title>edit_data_templateEditForm</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	</head>
	<body bgcolor="gray" text="#000000">
	     <?php 
			$id=$_GET['Data_temp_slno'];
			if(!isset($_GET['Data_temp_slno']))	 { echo 'Invalid_URL'; return true;}
			include_once("class.data_template.php");
			$tb_handle=new data_template();
			$tb_handle->select($id);
		?>


	<table width="480" border="1" align="center" height="269">
	  <tr>
	    <td height="234" colspan="2">
		 <form name='data_template_update_frm'  action='data_template_UpdateProcess.php' method=post>
		<input type=hidden size=30 name=Data_temp_slno id=Data_temp_slno value="<?php echo $tb_handle->getData_temp_slno();?>">
 		<table>	
		<tr><td>Data_temp_slno&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_slno name=Data_temp_slno value="<?php echo $tb_handle->getData_temp_slno();?>">
		</td></tr>	
		<tr><td>Data_temp_ Metric_slno&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ Metric_slno name=Data_temp_ Metric_slno value="<?php echo $tb_handle->getData_temp_ Metric_slno();?>">
		</td></tr>	
		<tr><td>Data_temp_ descrip&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ descrip name=Data_temp_ descrip value="<?php echo $tb_handle->getData_temp_ descrip();?>">
		</td></tr>	
		<tr><td>Data_temp_ status_block&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ status_block name=Data_temp_ status_block value="<?php echo $tb_handle->getData_temp_ status_block();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved1&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved1 name=Data_temp_ reserved1 value="<?php echo $tb_handle->getData_temp_ reserved1();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved2&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved2 name=Data_temp_ reserved2 value="<?php echo $tb_handle->getData_temp_ reserved2();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved3&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved3 name=Data_temp_ reserved3 value="<?php echo $tb_handle->getData_temp_ reserved3();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved4&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved4 name=Data_temp_ reserved4 value="<?php echo $tb_handle->getData_temp_ reserved4();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved5&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved5 name=Data_temp_ reserved5 value="<?php echo $tb_handle->getData_temp_ reserved5();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved6&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved6 name=Data_temp_ reserved6 value="<?php echo $tb_handle->getData_temp_ reserved6();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved7&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved7 name=Data_temp_ reserved7 value="<?php echo $tb_handle->getData_temp_ reserved7();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved8&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved8 name=Data_temp_ reserved8 value="<?php echo $tb_handle->getData_temp_ reserved8();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved9&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved9 name=Data_temp_ reserved9 value="<?php echo $tb_handle->getData_temp_ reserved9();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved10&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved10 name=Data_temp_ reserved10 value="<?php echo $tb_handle->getData_temp_ reserved10();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved11&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved11 name=Data_temp_ reserved11 value="<?php echo $tb_handle->getData_temp_ reserved11();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved12&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved12 name=Data_temp_ reserved12 value="<?php echo $tb_handle->getData_temp_ reserved12();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved13&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved13 name=Data_temp_ reserved13 value="<?php echo $tb_handle->getData_temp_ reserved13();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved14&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved14 name=Data_temp_ reserved14 value="<?php echo $tb_handle->getData_temp_ reserved14();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved15&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved15 name=Data_temp_ reserved15 value="<?php echo $tb_handle->getData_temp_ reserved15();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved16&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved16 name=Data_temp_ reserved16 value="<?php echo $tb_handle->getData_temp_ reserved16();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved17&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved17 name=Data_temp_ reserved17 value="<?php echo $tb_handle->getData_temp_ reserved17();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved18&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved18 name=Data_temp_ reserved18 value="<?php echo $tb_handle->getData_temp_ reserved18();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved19&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved19 name=Data_temp_ reserved19 value="<?php echo $tb_handle->getData_temp_ reserved19();?>">
		</td></tr>	
		<tr><td>Data_temp_ reserved20&nbsp;</td><td>
		<input type=text size=30 id=Data_temp_ reserved20 name=Data_temp_ reserved20 value="<?php echo $tb_handle->getData_temp_ reserved20();?>">
		</td></tr>	
		</table>		

	    </td>
	  </tr>
	</table>
       <p align=center> <input type=submit value="Update"></p>
	     </form>
      </body>
</html>