<!-- AutoGenerated Form Developed By *** B.Deka *** CopyRight Protection--> 
	<html>
	<head>
	<title>data_templateForm</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	</head>
	<body bgcolor="gray" text="#000000">
	<table width="480" border="1" align="center" height="269">
	  <tr>
	    <td height="234" colspan="2">
		 <form name=data_template_frm  action=data_templateFormProcess.php method=post>
 			 <table>	
				<tr><td>Data_temp_slno&nbsp;</td><td><input type=text size=30 name=Data_temp_slno id=Data_temp_slno></td></tr>	
				<tr><td>Data_temp_ Metric_slno&nbsp;</td><td><input type=text size=30 name=Data_temp_ Metric_slno id=Data_temp_ Metric_slno></td></tr>	
				<tr><td>Data_temp_ descrip&nbsp;</td><td><input type=text size=30 name=Data_temp_ descrip id=Data_temp_ descrip></td></tr>	
				<tr><td>Data_temp_ status_block&nbsp;</td><td><input type=text size=30 name=Data_temp_ status_block id=Data_temp_ status_block></td></tr>	
				<tr><td>Data_temp_ reserved1&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved1 id=Data_temp_ reserved1></td></tr>	
				<tr><td>Data_temp_ reserved2&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved2 id=Data_temp_ reserved2></td></tr>	
				<tr><td>Data_temp_ reserved3&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved3 id=Data_temp_ reserved3></td></tr>	
				<tr><td>Data_temp_ reserved4&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved4 id=Data_temp_ reserved4></td></tr>	
				<tr><td>Data_temp_ reserved5&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved5 id=Data_temp_ reserved5></td></tr>	
				<tr><td>Data_temp_ reserved6&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved6 id=Data_temp_ reserved6></td></tr>	
				<tr><td>Data_temp_ reserved7&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved7 id=Data_temp_ reserved7></td></tr>	
				<tr><td>Data_temp_ reserved8&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved8 id=Data_temp_ reserved8></td></tr>	
				<tr><td>Data_temp_ reserved9&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved9 id=Data_temp_ reserved9></td></tr>	
				<tr><td>Data_temp_ reserved10&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved10 id=Data_temp_ reserved10></td></tr>	
				<tr><td>Data_temp_ reserved11&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved11 id=Data_temp_ reserved11></td></tr>	
				<tr><td>Data_temp_ reserved12&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved12 id=Data_temp_ reserved12></td></tr>	
				<tr><td>Data_temp_ reserved13&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved13 id=Data_temp_ reserved13></td></tr>	
				<tr><td>Data_temp_ reserved14&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved14 id=Data_temp_ reserved14></td></tr>	
				<tr><td>Data_temp_ reserved15&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved15 id=Data_temp_ reserved15></td></tr>	
				<tr><td>Data_temp_ reserved16&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved16 id=Data_temp_ reserved16></td></tr>	
				<tr><td>Data_temp_ reserved17&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved17 id=Data_temp_ reserved17></td></tr>	
				<tr><td>Data_temp_ reserved18&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved18 id=Data_temp_ reserved18></td></tr>	
				<tr><td>Data_temp_ reserved19&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved19 id=Data_temp_ reserved19></td></tr>	
				<tr><td>Data_temp_ reserved20&nbsp;</td><td><input type=text size=30 name=Data_temp_ reserved20 id=Data_temp_ reserved20></td></tr>	
			</table>

		

	    </td>
	  </tr>
	</table>
        <p align=center><input type=submit value="Save"><input type=reset value="Reset"></p>
	</form>
      </body>
</html>