<!-- AutoGenerated Form Developed By *** B.Deka *** Copyright--> 
	<html>
	<head>
	<title>edit_data_template_uploadEditForm</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	</head>
	<body bgcolor="gray" text="#000000">
	     <?php 
			$id=$_GET['data_upload_slno'];
			if(!isset($_GET['data_upload_slno']))	 { echo 'Invalid_URL'; return true;}
			include_once("class.data_template_upload.php");
			$tb_handle=new data_template_upload();
			$tb_handle->select($id);
		?>


	<table width="480" border="1" align="center" height="269">
	  <tr>
	    <td height="234" colspan="2">
		 <form name='data_template_upload_update_frm'  action='data_template_upload_UpdateProcess.php' method=post>
		<input type=hidden size=30 name=data_upload_slno id=data_upload_slno value="<?php echo $tb_handle->getdata_upload_slno();?>">
 		<table>	
		<tr><td>data_upload_slno&nbsp;</td><td>
		<input type=text size=30 id=data_upload_slno name=data_upload_slno value="<?php echo $tb_handle->getdata_upload_slno();?>">
		</td></tr>	
		<tr><td>data_upload_temp_slno&nbsp;</td><td>
		<input type=text size=30 id=data_upload_temp_slno name=data_upload_temp_slno value="<?php echo $tb_handle->getdata_upload_temp_slno();?>">
		</td></tr>	
		<tr><td>data_upload_title&nbsp;</td><td>
		<input type=text size=30 id=data_upload_title name=data_upload_title value="<?php echo $tb_handle->getdata_upload_title();?>">
		</td></tr>	
		<tr><td>data_upload_url&nbsp;</td><td>
		<input type=text size=30 id=data_upload_url name=data_upload_url value="<?php echo $tb_handle->getdata_upload_url();?>">
		</td></tr>	
		<tr><td>data_upload_reserved1&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved1 name=data_upload_reserved1 value="<?php echo $tb_handle->getdata_upload_reserved1();?>">
		</td></tr>	
		<tr><td>data_upload_reserved2&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved2 name=data_upload_reserved2 value="<?php echo $tb_handle->getdata_upload_reserved2();?>">
		</td></tr>	
		<tr><td>data_upload_reserved3&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved3 name=data_upload_reserved3 value="<?php echo $tb_handle->getdata_upload_reserved3();?>">
		</td></tr>	
		<tr><td>data_upload_reserved4&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved4 name=data_upload_reserved4 value="<?php echo $tb_handle->getdata_upload_reserved4();?>">
		</td></tr>	
		<tr><td>data_upload_reserved5&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved5 name=data_upload_reserved5 value="<?php echo $tb_handle->getdata_upload_reserved5();?>">
		</td></tr>	
		<tr><td>data_upload_reserved6&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved6 name=data_upload_reserved6 value="<?php echo $tb_handle->getdata_upload_reserved6();?>">
		</td></tr>	
		<tr><td>data_upload_reserved7&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved7 name=data_upload_reserved7 value="<?php echo $tb_handle->getdata_upload_reserved7();?>">
		</td></tr>	
		<tr><td>data_upload_reserved8&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved8 name=data_upload_reserved8 value="<?php echo $tb_handle->getdata_upload_reserved8();?>">
		</td></tr>	
		<tr><td>data_upload_reserved9&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved9 name=data_upload_reserved9 value="<?php echo $tb_handle->getdata_upload_reserved9();?>">
		</td></tr>	
		<tr><td>data_upload_reserved10&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved10 name=data_upload_reserved10 value="<?php echo $tb_handle->getdata_upload_reserved10();?>">
		</td></tr>	
		<tr><td>data_upload_reserved11&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved11 name=data_upload_reserved11 value="<?php echo $tb_handle->getdata_upload_reserved11();?>">
		</td></tr>	
		<tr><td>data_upload_reserved12&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved12 name=data_upload_reserved12 value="<?php echo $tb_handle->getdata_upload_reserved12();?>">
		</td></tr>	
		<tr><td>data_upload_reserved13&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved13 name=data_upload_reserved13 value="<?php echo $tb_handle->getdata_upload_reserved13();?>">
		</td></tr>	
		<tr><td>data_upload_reserved14&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved14 name=data_upload_reserved14 value="<?php echo $tb_handle->getdata_upload_reserved14();?>">
		</td></tr>	
		<tr><td>data_upload_reserved15&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved15 name=data_upload_reserved15 value="<?php echo $tb_handle->getdata_upload_reserved15();?>">
		</td></tr>	
		<tr><td>data_upload_reserved16&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved16 name=data_upload_reserved16 value="<?php echo $tb_handle->getdata_upload_reserved16();?>">
		</td></tr>	
		<tr><td>data_upload_reserved17&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved17 name=data_upload_reserved17 value="<?php echo $tb_handle->getdata_upload_reserved17();?>">
		</td></tr>	
		<tr><td>data_upload_reserved18&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved18 name=data_upload_reserved18 value="<?php echo $tb_handle->getdata_upload_reserved18();?>">
		</td></tr>	
		<tr><td>data_upload_reserved19&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved19 name=data_upload_reserved19 value="<?php echo $tb_handle->getdata_upload_reserved19();?>">
		</td></tr>	
		<tr><td>data_upload_reserved20&nbsp;</td><td>
		<input type=text size=30 id=data_upload_reserved20 name=data_upload_reserved20 value="<?php echo $tb_handle->getdata_upload_reserved20();?>">
		</td></tr>	
		</table>		

	    </td>
	  </tr>
	</table>
       <p align=center> <input type=submit value="Update"></p>
	     </form>
      </body>
</html>