<!-- AutoGenerated Form Developed By *** B.Deka *** Copyright--> 
	<html>
	<head>
	<title>edit_keyindicatorEditForm</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	</head>
	<body bgcolor="gray" text="#000000">
	     <?php 
			$id=$_GET['key_slno'];
			if(!isset($_GET['key_slno']))	 { echo 'Invalid_URL'; return true;}
			include_once("class.keyindicator.php");
			$tb_handle=new keyindicator();
			$tb_handle->select($id);
		?>


	<table width="480" border="1" align="center" height="269">
	  <tr>
	    <td height="234" colspan="2">
		 <form name='keyindicator_update_frm'  action='keyindicator_UpdateProcess.php' method=post>
		<input type=hidden size=30 name=key_slno id=key_slno value="<?php echo $tb_handle->getkey_slno();?>">
 		<table>	
		<tr><td>key_slno&nbsp;</td><td>
		<input type=text size=30 id=key_slno name=key_slno value="<?php echo $tb_handle->getkey_slno();?>">
		</td></tr>	
		<tr><td>key_indicator&nbsp;</td><td>
		<input type=text size=30 id=key_indicator name=key_indicator value="<?php echo $tb_handle->getkey_indicator();?>">
		</td></tr>	
		<tr><td>key_title&nbsp;</td><td>
		<input type=text size=30 id=key_title name=key_title value="<?php echo $tb_handle->getkey_title();?>">
		</td></tr>	
		<tr><td>key_crite_slno&nbsp;</td><td>
		<input type=text size=30 id=key_crite_slno name=key_crite_slno value="<?php echo $tb_handle->getkey_crite_slno();?>">
		</td></tr>	
		<tr><td>key_block&nbsp;</td><td>
		<input type=text size=30 id=key_block name=key_block value="<?php echo $tb_handle->getkey_block();?>">
		</td></tr>	
		<tr><td>key_reserved1&nbsp;</td><td>
		<input type=text size=30 id=key_reserved1 name=key_reserved1 value="<?php echo $tb_handle->getkey_reserved1();?>">
		</td></tr>	
		<tr><td>key_reserved2&nbsp;</td><td>
		<input type=text size=30 id=key_reserved2 name=key_reserved2 value="<?php echo $tb_handle->getkey_reserved2();?>">
		</td></tr>	
		<tr><td>key_reserved3&nbsp;</td><td>
		<input type=text size=30 id=key_reserved3 name=key_reserved3 value="<?php echo $tb_handle->getkey_reserved3();?>">
		</td></tr>	
		<tr><td>key_reserved4&nbsp;</td><td>
		<input type=text size=30 id=key_reserved4 name=key_reserved4 value="<?php echo $tb_handle->getkey_reserved4();?>">
		</td></tr>	
		<tr><td>key_reserved5&nbsp;</td><td>
		<input type=text size=30 id=key_reserved5 name=key_reserved5 value="<?php echo $tb_handle->getkey_reserved5();?>">
		</td></tr>	
		<tr><td>key_reserved6&nbsp;</td><td>
		<input type=text size=30 id=key_reserved6 name=key_reserved6 value="<?php echo $tb_handle->getkey_reserved6();?>">
		</td></tr>	
		<tr><td>key_reserved7&nbsp;</td><td>
		<input type=text size=30 id=key_reserved7 name=key_reserved7 value="<?php echo $tb_handle->getkey_reserved7();?>">
		</td></tr>	
		<tr><td>key_reserved8&nbsp;</td><td>
		<input type=text size=30 id=key_reserved8 name=key_reserved8 value="<?php echo $tb_handle->getkey_reserved8();?>">
		</td></tr>	
		<tr><td>key_reserved9&nbsp;</td><td>
		<input type=text size=30 id=key_reserved9 name=key_reserved9 value="<?php echo $tb_handle->getkey_reserved9();?>">
		</td></tr>	
		<tr><td>key_reserved10&nbsp;</td><td>
		<input type=text size=30 id=key_reserved10 name=key_reserved10 value="<?php echo $tb_handle->getkey_reserved10();?>">
		</td></tr>	
		<tr><td>key_reserved11&nbsp;</td><td>
		<input type=text size=30 id=key_reserved11 name=key_reserved11 value="<?php echo $tb_handle->getkey_reserved11();?>">
		</td></tr>	
		<tr><td>key_reserved12&nbsp;</td><td>
		<input type=text size=30 id=key_reserved12 name=key_reserved12 value="<?php echo $tb_handle->getkey_reserved12();?>">
		</td></tr>	
		<tr><td>key_reserved13&nbsp;</td><td>
		<input type=text size=30 id=key_reserved13 name=key_reserved13 value="<?php echo $tb_handle->getkey_reserved13();?>">
		</td></tr>	
		<tr><td>key_reserved14&nbsp;</td><td>
		<input type=text size=30 id=key_reserved14 name=key_reserved14 value="<?php echo $tb_handle->getkey_reserved14();?>">
		</td></tr>	
		<tr><td>key_reserved15&nbsp;</td><td>
		<input type=text size=30 id=key_reserved15 name=key_reserved15 value="<?php echo $tb_handle->getkey_reserved15();?>">
		</td></tr>	
		<tr><td>key_reserved16&nbsp;</td><td>
		<input type=text size=30 id=key_reserved16 name=key_reserved16 value="<?php echo $tb_handle->getkey_reserved16();?>">
		</td></tr>	
		<tr><td>key_reserved17&nbsp;</td><td>
		<input type=text size=30 id=key_reserved17 name=key_reserved17 value="<?php echo $tb_handle->getkey_reserved17();?>">
		</td></tr>	
		<tr><td>key_reserved18&nbsp;</td><td>
		<input type=text size=30 id=key_reserved18 name=key_reserved18 value="<?php echo $tb_handle->getkey_reserved18();?>">
		</td></tr>	
		<tr><td>key_reserved19&nbsp;</td><td>
		<input type=text size=30 id=key_reserved19 name=key_reserved19 value="<?php echo $tb_handle->getkey_reserved19();?>">
		</td></tr>	
		<tr><td>key_reserved20&nbsp;</td><td>
		<input type=text size=30 id=key_reserved20 name=key_reserved20 value="<?php echo $tb_handle->getkey_reserved20();?>">
		</td></tr>	
		</table>		

	    </td>
	  </tr>
	</table>
       <p align=center> <input type=submit value="Update"></p>
	     </form>
      </body>
</html>