<!-- AutoGenerated Form Developed By *** B.Deka *** CopyRight Protection--> 
	<html>
	<head>
	<title>keyindicatorForm</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	</head>
	<body bgcolor="gray" text="#000000">
	<table width="480" border="1" align="center" height="269">
	  <tr>
	    <td height="234" colspan="2">
		 <form name=keyindicator_frm  action=keyindicatorFormProcess.php method=post>
 			 <table>	
				<tr><td>key_slno&nbsp;</td><td><input type=text size=30 name=key_slno id=key_slno></td></tr>	
				<tr><td>key_indicator&nbsp;</td><td><input type=text size=30 name=key_indicator id=key_indicator></td></tr>	
				<tr><td>key_title&nbsp;</td><td><input type=text size=30 name=key_title id=key_title></td></tr>	
				<tr><td>key_crite_slno&nbsp;</td><td><input type=text size=30 name=key_crite_slno id=key_crite_slno></td></tr>	
				<tr><td>key_block&nbsp;</td><td><input type=text size=30 name=key_block id=key_block></td></tr>	
				<tr><td>key_reserved1&nbsp;</td><td><input type=text size=30 name=key_reserved1 id=key_reserved1></td></tr>	
				<tr><td>key_reserved2&nbsp;</td><td><input type=text size=30 name=key_reserved2 id=key_reserved2></td></tr>	
				<tr><td>key_reserved3&nbsp;</td><td><input type=text size=30 name=key_reserved3 id=key_reserved3></td></tr>	
				<tr><td>key_reserved4&nbsp;</td><td><input type=text size=30 name=key_reserved4 id=key_reserved4></td></tr>	
				<tr><td>key_reserved5&nbsp;</td><td><input type=text size=30 name=key_reserved5 id=key_reserved5></td></tr>	
				<tr><td>key_reserved6&nbsp;</td><td><input type=text size=30 name=key_reserved6 id=key_reserved6></td></tr>	
				<tr><td>key_reserved7&nbsp;</td><td><input type=text size=30 name=key_reserved7 id=key_reserved7></td></tr>	
				<tr><td>key_reserved8&nbsp;</td><td><input type=text size=30 name=key_reserved8 id=key_reserved8></td></tr>	
				<tr><td>key_reserved9&nbsp;</td><td><input type=text size=30 name=key_reserved9 id=key_reserved9></td></tr>	
				<tr><td>key_reserved10&nbsp;</td><td><input type=text size=30 name=key_reserved10 id=key_reserved10></td></tr>	
				<tr><td>key_reserved11&nbsp;</td><td><input type=text size=30 name=key_reserved11 id=key_reserved11></td></tr>	
				<tr><td>key_reserved12&nbsp;</td><td><input type=text size=30 name=key_reserved12 id=key_reserved12></td></tr>	
				<tr><td>key_reserved13&nbsp;</td><td><input type=text size=30 name=key_reserved13 id=key_reserved13></td></tr>	
				<tr><td>key_reserved14&nbsp;</td><td><input type=text size=30 name=key_reserved14 id=key_reserved14></td></tr>	
				<tr><td>key_reserved15&nbsp;</td><td><input type=text size=30 name=key_reserved15 id=key_reserved15></td></tr>	
				<tr><td>key_reserved16&nbsp;</td><td><input type=text size=30 name=key_reserved16 id=key_reserved16></td></tr>	
				<tr><td>key_reserved17&nbsp;</td><td><input type=text size=30 name=key_reserved17 id=key_reserved17></td></tr>	
				<tr><td>key_reserved18&nbsp;</td><td><input type=text size=30 name=key_reserved18 id=key_reserved18></td></tr>	
				<tr><td>key_reserved19&nbsp;</td><td><input type=text size=30 name=key_reserved19 id=key_reserved19></td></tr>	
				<tr><td>key_reserved20&nbsp;</td><td><input type=text size=30 name=key_reserved20 id=key_reserved20></td></tr>	
			</table>

		

	    </td>
	  </tr>
	</table>
        <p align=center><input type=submit value="Save"><input type=reset value="Reset"></p>
	</form>
      </body>
</html>