<!-- AutoGenerated Form Developed By *** B.Deka *** Copyright--> 
	<html>
	<head>
	<title>edit_metricuploadEditForm</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	</head>
	<body bgcolor="gray" text="#000000">
	     <?php 
			$id=$_GET['up_metric_slno'];
			if(!isset($_GET['up_metric_slno']))	 { echo 'Invalid_URL'; return true;}
			include_once("class.metricupload.php");
			$tb_handle=new metricupload();
			$tb_handle->select($id);
		?>


	<table width="480" border="1" align="center" height="269">
	  <tr>
	    <td height="234" colspan="2">
		 <form name='metricupload_update_frm'  action='metricupload_UpdateProcess.php' method=post>
		<input type=hidden size=30 name=up_metric_slno id=up_metric_slno value="<?php echo $tb_handle->getup_metric_slno();?>">
 		<table>	
		<tr><td>up_metric_slno&nbsp;</td><td>
		<input type=text size=30 id=up_metric_slno name=up_metric_slno value="<?php echo $tb_handle->getup_metric_slno();?>">
		</td></tr>	
		<tr><td>up_metric_metric_slno&nbsp;</td><td>
		<input type=text size=30 id=up_metric_metric_slno name=up_metric_metric_slno value="<?php echo $tb_handle->getup_metric_metric_slno();?>">
		</td></tr>	
		<tr><td>up_metric_title&nbsp;</td><td>
		<input type=text size=30 id=up_metric_title name=up_metric_title value="<?php echo $tb_handle->getup_metric_title();?>">
		</td></tr>	
		<tr><td>up_metric_url&nbsp;</td><td>
		<input type=text size=30 id=up_metric_url name=up_metric_url value="<?php echo $tb_handle->getup_metric_url();?>">
		</td></tr>	
		<tr><td>up_metric_block&nbsp;</td><td>
		<input type=text size=30 id=up_metric_block name=up_metric_block value="<?php echo $tb_handle->getup_metric_block();?>">
		</td></tr>	
		<tr><td>up_metric_reserved1&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved1 name=up_metric_reserved1 value="<?php echo $tb_handle->getup_metric_reserved1();?>">
		</td></tr>	
		<tr><td>up_metric_reserved2&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved2 name=up_metric_reserved2 value="<?php echo $tb_handle->getup_metric_reserved2();?>">
		</td></tr>	
		<tr><td>up_metric_reserved3&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved3 name=up_metric_reserved3 value="<?php echo $tb_handle->getup_metric_reserved3();?>">
		</td></tr>	
		<tr><td>up_metric_reserved4&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved4 name=up_metric_reserved4 value="<?php echo $tb_handle->getup_metric_reserved4();?>">
		</td></tr>	
		<tr><td>up_metric_reserved5&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved5 name=up_metric_reserved5 value="<?php echo $tb_handle->getup_metric_reserved5();?>">
		</td></tr>	
		<tr><td>up_metric_reserved6&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved6 name=up_metric_reserved6 value="<?php echo $tb_handle->getup_metric_reserved6();?>">
		</td></tr>	
		<tr><td>up_metric_reserved7&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved7 name=up_metric_reserved7 value="<?php echo $tb_handle->getup_metric_reserved7();?>">
		</td></tr>	
		<tr><td>up_metric_reserved8&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved8 name=up_metric_reserved8 value="<?php echo $tb_handle->getup_metric_reserved8();?>">
		</td></tr>	
		<tr><td>up_metric_reserved9&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved9 name=up_metric_reserved9 value="<?php echo $tb_handle->getup_metric_reserved9();?>">
		</td></tr>	
		<tr><td>up_metric_reserved10&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved10 name=up_metric_reserved10 value="<?php echo $tb_handle->getup_metric_reserved10();?>">
		</td></tr>	
		<tr><td>up_metric_reserved11&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved11 name=up_metric_reserved11 value="<?php echo $tb_handle->getup_metric_reserved11();?>">
		</td></tr>	
		<tr><td>up_metric_reserved12&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved12 name=up_metric_reserved12 value="<?php echo $tb_handle->getup_metric_reserved12();?>">
		</td></tr>	
		<tr><td>up_metric_reserved13&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved13 name=up_metric_reserved13 value="<?php echo $tb_handle->getup_metric_reserved13();?>">
		</td></tr>	
		<tr><td>up_metric_reserved14&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved14 name=up_metric_reserved14 value="<?php echo $tb_handle->getup_metric_reserved14();?>">
		</td></tr>	
		<tr><td>up_metric_reserved15&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved15 name=up_metric_reserved15 value="<?php echo $tb_handle->getup_metric_reserved15();?>">
		</td></tr>	
		<tr><td>up_metric_reserved16&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved16 name=up_metric_reserved16 value="<?php echo $tb_handle->getup_metric_reserved16();?>">
		</td></tr>	
		<tr><td>up_metric_reserved17&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved17 name=up_metric_reserved17 value="<?php echo $tb_handle->getup_metric_reserved17();?>">
		</td></tr>	
		<tr><td>up_metric_reserved18&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved18 name=up_metric_reserved18 value="<?php echo $tb_handle->getup_metric_reserved18();?>">
		</td></tr>	
		<tr><td>up_metric_reserved19&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved19 name=up_metric_reserved19 value="<?php echo $tb_handle->getup_metric_reserved19();?>">
		</td></tr>	
		<tr><td>up_metric_reserved20&nbsp;</td><td>
		<input type=text size=30 id=up_metric_reserved20 name=up_metric_reserved20 value="<?php echo $tb_handle->getup_metric_reserved20();?>">
		</td></tr>	
		</table>		

	    </td>
	  </tr>
	</table>
       <p align=center> <input type=submit value="Update"></p>
	     </form>
      </body>
</html>