<!-- AutoGenerated Form Developed By *** B.Deka *** Copyright--> 
	<html>
	<head>
	<title>edit_metrictableEditForm</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	</head>
	<body bgcolor="gray" text="#000000">
	     <?php 
			$id=$_GET['metric_slno'];
			if(!isset($_GET['metric_slno']))	 { echo 'Invalid_URL'; return true;}
			include_once("class.metrictable.php");
			$tb_handle=new metrictable();
			$tb_handle->select($id);
		?>


	<table width="480" border="1" align="center" height="269">
	  <tr>
	    <td height="234" colspan="2">
		 <form name='metrictable_update_frm'  action='metrictable_UpdateProcess.php' method=post>
		<input type=hidden size=30 name=metric_slno id=metric_slno value="<?php echo $tb_handle->getmetric_slno();?>">
 		<table>	
		<tr><td>metric_slno&nbsp;</td><td>
		<input type=text size=30 id=metric_slno name=metric_slno value="<?php echo $tb_handle->getmetric_slno();?>">
		</td></tr>	
		<tr><td>metric_no&nbsp;</td><td>
		<input type=text size=30 id=metric_no name=metric_no value="<?php echo $tb_handle->getmetric_no();?>">
		</td></tr>	
		<tr><td>metric_title&nbsp;</td><td>
		<input type=text size=30 id=metric_title name=metric_title value="<?php echo $tb_handle->getmetric_title();?>">
		</td></tr>	
		<tr><td>metric_details&nbsp;</td><td>
		<input type=text size=30 id=metric_details name=metric_details value="<?php echo $tb_handle->getmetric_details();?>">
		</td></tr>	
		<tr><td>metric_key_slno&nbsp;</td><td>
		<input type=text size=30 id=metric_key_slno name=metric_key_slno value="<?php echo $tb_handle->getmetric_key_slno();?>">
		</td></tr>	
		<tr><td>metric_block&nbsp;</td><td>
		<input type=text size=30 id=metric_block name=metric_block value="<?php echo $tb_handle->getmetric_block();?>">
		</td></tr>	
		<tr><td>metric_reserved1&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved1 name=metric_reserved1 value="<?php echo $tb_handle->getmetric_reserved1();?>">
		</td></tr>	
		<tr><td>metric_reserved2&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved2 name=metric_reserved2 value="<?php echo $tb_handle->getmetric_reserved2();?>">
		</td></tr>	
		<tr><td>metric_reserved3&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved3 name=metric_reserved3 value="<?php echo $tb_handle->getmetric_reserved3();?>">
		</td></tr>	
		<tr><td>metric_reserved4&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved4 name=metric_reserved4 value="<?php echo $tb_handle->getmetric_reserved4();?>">
		</td></tr>	
		<tr><td>metric_reserved5&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved5 name=metric_reserved5 value="<?php echo $tb_handle->getmetric_reserved5();?>">
		</td></tr>	
		<tr><td>metric_reserved6&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved6 name=metric_reserved6 value="<?php echo $tb_handle->getmetric_reserved6();?>">
		</td></tr>	
		<tr><td>metric_reserved7&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved7 name=metric_reserved7 value="<?php echo $tb_handle->getmetric_reserved7();?>">
		</td></tr>	
		<tr><td>metric_reserved8&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved8 name=metric_reserved8 value="<?php echo $tb_handle->getmetric_reserved8();?>">
		</td></tr>	
		<tr><td>metric_reserved9&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved9 name=metric_reserved9 value="<?php echo $tb_handle->getmetric_reserved9();?>">
		</td></tr>	
		<tr><td>metric_reserved10&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved10 name=metric_reserved10 value="<?php echo $tb_handle->getmetric_reserved10();?>">
		</td></tr>	
		<tr><td>metric_reserved11&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved11 name=metric_reserved11 value="<?php echo $tb_handle->getmetric_reserved11();?>">
		</td></tr>	
		<tr><td>metric_reserved12&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved12 name=metric_reserved12 value="<?php echo $tb_handle->getmetric_reserved12();?>">
		</td></tr>	
		<tr><td>metric_reserved13&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved13 name=metric_reserved13 value="<?php echo $tb_handle->getmetric_reserved13();?>">
		</td></tr>	
		<tr><td>metric_reserved14&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved14 name=metric_reserved14 value="<?php echo $tb_handle->getmetric_reserved14();?>">
		</td></tr>	
		<tr><td>metric_reserved15&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved15 name=metric_reserved15 value="<?php echo $tb_handle->getmetric_reserved15();?>">
		</td></tr>	
		<tr><td>metric_reserved16&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved16 name=metric_reserved16 value="<?php echo $tb_handle->getmetric_reserved16();?>">
		</td></tr>	
		<tr><td>metric_reserved17&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved17 name=metric_reserved17 value="<?php echo $tb_handle->getmetric_reserved17();?>">
		</td></tr>	
		<tr><td>metric_reserved18&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved18 name=metric_reserved18 value="<?php echo $tb_handle->getmetric_reserved18();?>">
		</td></tr>	
		<tr><td>metric_reserved19&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved19 name=metric_reserved19 value="<?php echo $tb_handle->getmetric_reserved19();?>">
		</td></tr>	
		<tr><td>metric_reserved20&nbsp;</td><td>
		<input type=text size=30 id=metric_reserved20 name=metric_reserved20 value="<?php echo $tb_handle->getmetric_reserved20();?>">
		</td></tr>	
		</table>		

	    </td>
	  </tr>
	</table>
       <p align=center> <input type=submit value="Update"></p>
	     </form>
      </body>
</html>