<!-- AutoGenerated Form Developed By *** B.Deka *** CopyRight Protection--> 
	<html>
	<head>
	<title>metricuploadForm</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	</head>
	<body bgcolor="gray" text="#000000">
	<table width="480" border="1" align="center" height="269">
	  <tr>
	    <td height="234" colspan="2">
		 <form name=metricupload_frm  action=metricuploadFormProcess.php method=post>
 			 <table>	
				<tr><td>up_metric_slno&nbsp;</td><td><input type=text size=30 name=up_metric_slno id=up_metric_slno></td></tr>	
				<tr><td>up_metric_metric_slno&nbsp;</td><td><input type=text size=30 name=up_metric_metric_slno id=up_metric_metric_slno></td></tr>	
				<tr><td>up_metric_title&nbsp;</td><td><input type=text size=30 name=up_metric_title id=up_metric_title></td></tr>	
				<tr><td>up_metric_url&nbsp;</td><td><input type=text size=30 name=up_metric_url id=up_metric_url></td></tr>	
				<tr><td>up_metric_block&nbsp;</td><td><input type=text size=30 name=up_metric_block id=up_metric_block></td></tr>	
				<tr><td>up_metric_reserved1&nbsp;</td><td><input type=text size=30 name=up_metric_reserved1 id=up_metric_reserved1></td></tr>	
				<tr><td>up_metric_reserved2&nbsp;</td><td><input type=text size=30 name=up_metric_reserved2 id=up_metric_reserved2></td></tr>	
				<tr><td>up_metric_reserved3&nbsp;</td><td><input type=text size=30 name=up_metric_reserved3 id=up_metric_reserved3></td></tr>	
				<tr><td>up_metric_reserved4&nbsp;</td><td><input type=text size=30 name=up_metric_reserved4 id=up_metric_reserved4></td></tr>	
				<tr><td>up_metric_reserved5&nbsp;</td><td><input type=text size=30 name=up_metric_reserved5 id=up_metric_reserved5></td></tr>	
				<tr><td>up_metric_reserved6&nbsp;</td><td><input type=text size=30 name=up_metric_reserved6 id=up_metric_reserved6></td></tr>	
				<tr><td>up_metric_reserved7&nbsp;</td><td><input type=text size=30 name=up_metric_reserved7 id=up_metric_reserved7></td></tr>	
				<tr><td>up_metric_reserved8&nbsp;</td><td><input type=text size=30 name=up_metric_reserved8 id=up_metric_reserved8></td></tr>	
				<tr><td>up_metric_reserved9&nbsp;</td><td><input type=text size=30 name=up_metric_reserved9 id=up_metric_reserved9></td></tr>	
				<tr><td>up_metric_reserved10&nbsp;</td><td><input type=text size=30 name=up_metric_reserved10 id=up_metric_reserved10></td></tr>	
				<tr><td>up_metric_reserved11&nbsp;</td><td><input type=text size=30 name=up_metric_reserved11 id=up_metric_reserved11></td></tr>	
				<tr><td>up_metric_reserved12&nbsp;</td><td><input type=text size=30 name=up_metric_reserved12 id=up_metric_reserved12></td></tr>	
				<tr><td>up_metric_reserved13&nbsp;</td><td><input type=text size=30 name=up_metric_reserved13 id=up_metric_reserved13></td></tr>	
				<tr><td>up_metric_reserved14&nbsp;</td><td><input type=text size=30 name=up_metric_reserved14 id=up_metric_reserved14></td></tr>	
				<tr><td>up_metric_reserved15&nbsp;</td><td><input type=text size=30 name=up_metric_reserved15 id=up_metric_reserved15></td></tr>	
				<tr><td>up_metric_reserved16&nbsp;</td><td><input type=text size=30 name=up_metric_reserved16 id=up_metric_reserved16></td></tr>	
				<tr><td>up_metric_reserved17&nbsp;</td><td><input type=text size=30 name=up_metric_reserved17 id=up_metric_reserved17></td></tr>	
				<tr><td>up_metric_reserved18&nbsp;</td><td><input type=text size=30 name=up_metric_reserved18 id=up_metric_reserved18></td></tr>	
				<tr><td>up_metric_reserved19&nbsp;</td><td><input type=text size=30 name=up_metric_reserved19 id=up_metric_reserved19></td></tr>	
				<tr><td>up_metric_reserved20&nbsp;</td><td><input type=text size=30 name=up_metric_reserved20 id=up_metric_reserved20></td></tr>	
			</table>

		

	    </td>
	  </tr>
	</table>
        <p align=center><input type=submit value="Save"><input type=reset value="Reset"></p>
	</form>
      </body>
</html>